### ISSUE TITLE
[Discussion] Test execution

### ISSUE THREAD

**Issue by blaggacao** [Tecnativa/docker-odoo-base#14] opened 2017-02-13 18:28 UTC
I find MQT quite handy up to certain extent (it's a monolithic metamorph) in order to execute testing, however preparing my local test bed is a pain and I am split brain among improving MQT or factoring out part of its' ideas into something like what you started here.

What I like:

- Being able to build a template DB to speed things up
- Being able to autodetect changes via a git reflog analysis, so it at leasts always tests automatically the modules I touched.
- Keeping DB up and running, so it can soon double up as a more Standard-CI/CD friendly runbot replacement.

What I don't like there:

- Architecture and design are somewhat erratic and constantly changing.
- It has the OCA way in mind without being too much extensible
- A point I don't want to speak publically about 😸 - ok it has to do with time investment and iterations...

So the question is: "make or buy"? (or drop, obviously)

**Comment by Yajo** [comment] 2017-02-27 10:31
Hmm CI/CD is something I have in my TODO list, but it's some steps away from here in our internal roadmap on this subject, so I fear I cannot help you too much for the time being. @lasley is way ahead of me into it.

From a general (and newbie) POV, you have 2 paths:

- Try to integrate those tools into this base image.
- Create a different Docker image specifically made for testing with MQT, and add a `testing.yaml` environment to the base scaffolding.

As I said, I'm afraid my present self is not the guy that can help you in this particular subject, but certainly I will be happy to review/merge PRs to this project 😉.

**Comment by lasley** [comment] 2017-06-10 02:13
Oh hi! Missed this!

We actually have a few completely basic MQT type things:

* [docker-quality-tools](https://github.com/LasLabs/docker-quality-tools)
* [python-quality-tools](https://github.com/LasLabs/python-quality-tools)

We're in the process of upgrading the Docker one to use compose files, which is the norm for Docker CI. I didn't know that at the time, so it's a work item.

That said, we have an [Odoo Docker image](https://github.com/LasLabs/docker-odoo) that is tested:
* https://github.com/LasLabs/docker-odoo/tree/master/tests
* https://github.com/LasLabs/docker-odoo/blob/master/.travis.yml

Really it's just a matter of building the image in the Travis, then creating a `tests` folder of executables to do whatever it is you want to do.

I just started messing with this repo again for some new buildouts, so I may get around to testing it. I'm totally overloaded though & I don't have an actual ticket open, so it's unfortunately likely I'll forget 😑

**Comment by Yajo** [comment] 2017-06-12 08:09
Yikes, this is growing faster that I can handle 😅 

Will add CI ASAP, PRs welcome for now 😉

**Comment by Yajo** [comment] 2017-06-14 07:34
Seems like discussion ended, and the rest is a duplicate of #6.

**Closed by Yajo** 2017-06-14 07:34 UTC
Labels: enhancement, help wanted
